services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    
    # Build command
    buildCommand: echo "Building Laravel app..."
    
    # Health check
    healthCheckPath: /health
    
    envVars:
      - key: PORT
        value: 10000
      - key: APP_NAME
        value: DataGenerator
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: array
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: errorlog
      
      # Database variables
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password

databases:
  - name: laravel-db
    plan: free